In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/abalone.data')
df

M  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
0     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [23]:
df.columns = ["Sex",	"Length",	"Diameter",	"Height",	"Whole weight",	"Shucked weight",	"Viscera weight",	"Shell weight",	"Rings"]
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.350     0.265   0.090        0.2255          0.0995   
1      F   0.530     0.420   0.135        0.6770          0.2565   
2      M   0.440     0.365   0.125        0.5160          0.2155   
3      I   0.330     0.255   0.080        0.2050          0.0895   
4      I   0.425     0.300   0.095        0.3515          0.1410   
...   ..     ...       ...     ...           ...             ...   
4171   F   0.565     0.450   0.165        0.8870          0.3700   
4172   M   0.590     0.440   0.135        0.9660          0.4390   
4173   M   0.600     0.475   0.205        1.1760          0.5255   
4174   F   0.625     0.485   0.150        1.0945          0.5310   
4175   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.0485        0.0700      7  
1             0.1415        0.2100      9  
2             0.1140        0.1550     10  
3             0.0395        0.0550      7  
4             0.0775        0.1200      8  
...              ...           ...    ...  
4171          0.2390        0.2490     11  
4172          0.2145        0.2605     10  
4173          0.2875        0.3080      9  
4174          0.2610        0.2960     10  
4175          0.3765        0.4950     12  

[4176 rows x 9 columns]

In [24]:
x= df.drop('Rings',axis=1)
x

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.350     0.265   0.090        0.2255          0.0995   
1      F   0.530     0.420   0.135        0.6770          0.2565   
2      M   0.440     0.365   0.125        0.5160          0.2155   
3      I   0.330     0.255   0.080        0.2050          0.0895   
4      I   0.425     0.300   0.095        0.3515          0.1410   
...   ..     ...       ...     ...           ...             ...   
4171   F   0.565     0.450   0.165        0.8870          0.3700   
4172   M   0.590     0.440   0.135        0.9660          0.4390   
4173   M   0.600     0.475   0.205        1.1760          0.5255   
4174   F   0.625     0.485   0.150        1.0945          0.5310   
4175   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  
0             0.0485        0.0700  
1             0.1415        0.2100  
2             0.1140        0.1550  
3             0.0395        0.0550  
4             0.0775        0.1200  
...              ...           ...  
4171          0.2390        0.2490  
4172          0.2145        0.2605  
4173          0.2875        0.3080  
4174          0.2610        0.2960  
4175          0.3765        0.4950  

[4176 rows x 8 columns]

In [ ]:

y = df['Rings']
y

Sex
M    15
M     7
F     9
M    10
I     7
     ..
F    11
M    10
M     9
F    10
M    12
Name: Rings, Length: 4177, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3132, 7), (1045, 7), (3132,), (1045,))

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.2698564593301435
[[ 0  5  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  1  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  1 24  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0 21 27  9  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17 43 39 13  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6 14 72 36 10  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 10 29 69 38  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  5 21 43 46 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  6 16 29 42 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1 14 22 41 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  9 20 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4 11 13  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6 13  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  

In [ ]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.2535885167464115
[[ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 30  8  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17 32  9  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  7 44 41 20  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4 15 56 54  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  9 22 82 35  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  9 19 47 43 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  5 16 36 38 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1 12 26 36 17  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  7  7 23 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  8 14  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.184688995215311
[[ 1  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  5  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 14  7  8  7  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  6 16 21 10  3  0  0  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  2 25 33 29 12  5  3  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  6 25 34 35 21  5  4  4  1  1  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  8 22 40 31 21  9  5  3  3  2  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  9 20 30 23 20 13 12  4  2  4  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  6 13 23 31 18  9 11  4  0  1  1  2  0  0  1  0  0  0  0  0]
 [ 0  0  0  1  2 12 15 18 12  9 10  3  5  0  0  2  2  1  1  0  0  0  0  0]
 [ 0  0  0  0  2  3  7  8 11  5  5  2  2  2  1  1  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  4  6  4  4  3  1  3  2  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  3  4  1  3  2  1  0  3  

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))



--- Random Forest ---
0.24880382775119617
[[ 1  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  6  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10 13 11  4  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  6 23 17 13  2  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 23 41 31 10  5  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  6 25 58 29 13  5  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 37 37 43 16  4  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  5 17 28 42 26  5  9  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 13 31 33 26  3  4  4  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1 10 23 21 18  7  7  1  0  3  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  7 15 14  1  3  4  1  0  1  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  6  7  7  1  3  2  2  1  1  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  4  8  4  2  1  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  